version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
